# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  # ART tokens
  - addressOrDenom: "0x0a78BC3CBBC79C4C6E5d4e5b2bbD042E58e93484"
    chainName: artela
    coinGeckoId: usd-coin
    connections:
      - token: ethereum|base|0x228c5101b2C63b9d620a3e8FEa7eC14263F82569
    decimals: 18
    logoURI: /deployments/warp_routes/ART/logo.svg
    name: Artela
    standard: EvmHypNative
    symbol: ART
  - addressOrDenom: "0x228c5101b2C63b9d620a3e8FEa7eC14263F82569"
    chainName: base
    connections:
      - token: ethereum|artela|0x0a78BC3CBBC79C4C6E5d4e5b2bbD042E58e93484
    decimals: 18
    logoURI: /deployments/warp_routes/ART/logo.svg
    name: Artela
    standard: EvmHypSynthetic
    symbol: ART

  # USDC tokens
  - addressOrDenom: "0x8d9Bd7E9ec3cd799a659EE650DfF6C799309fA91"
    chainName: artela
    connections:
      - token: ethereum|base|0x01348F639D6e418A5a9673c08c0dDf6ecCB80F37
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypSynthetic
    symbol: USDC.a
  - addressOrDenom: "0x01348F639D6e418A5a9673c08c0dDf6ecCB80F37"
    chainName: base
    coinGeckoId: usd-coin
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|artela|0x8d9Bd7E9ec3cd799a659EE650DfF6C799309fA91
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USD Coin
    standard: EvmHypCollateral
    symbol: USDC

  # WETH tokens
  - addressOrDenom: "0xfae4e14D01D9E13FB5db20A0329ED0472A2D96C7"
    chainName: artela
    connections:
      - token: ethereum|base|0x5B4d7FD7E6Cb11170137df1A0dB24645533EC0b5
    decimals: 18
    logoURI: /deployments/warp_routes/WETH/logo.svg
    name: Wrapped Ether
    standard: EvmHypSynthetic
    symbol: WETH.a
  - addressOrDenom: "0x5B4d7FD7E6Cb11170137df1A0dB24645533EC0b5"
    chainName: base
    coinGeckoId: l2-standard-bridged-weth-base
    collateralAddressOrDenom: "0x4200000000000000000000000000000000000006"
    connections:
      - token: ethereum|artela|0xfae4e14D01D9E13FB5db20A0329ED0472A2D96C7
    decimals: 18
    logoURI: /deployments/warp_routes/WETH/logo.svg
    name: Wrapped Ether
    standard: EvmHypCollateral
    symbol: WETH
options: {}